name: Build and Publish image

on:
  push:
    branches:
      - main
      - sandbox
  pull_request:
    branches:
      - main
      - sandbox

jobs:
  buildAndPushImage:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Set up Node
        uses: actions/setup-node@v6
        with:
          node-version: 24
      - uses: actions/cache@v5
        if: github.ref_name != 'main'
        with:
          path: /tmp/gulp-cache
          key: ${{ runner.os }}-gulp-cache
      - name: Build Frontend (Production)
        if: github.ref_name == 'main'
        run: |
          npm install
          gulp buildProduction
      - name: Build Frontend
        if: github.ref_name != 'main'
        run: |
          npm install
          gulp build
      - name: Log in to container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Collect image metadata
        uses: docker/metadata-action@v5
        id: image-metadata
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=raw,priority=1000,value=latest,enable=${{ github.ref_name == 'main' }}
            type=ref,event=branch
            type=ref,event=tag
            type=ref,event=pr
            type=raw,value=${{ github.run_id }}
      - name: Build and push images
        uses: docker/build-push-action@v6
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.image-metadata.outputs.tags }}
          labels: ${{ steps.image-metadata.outputs.labels }}
  cleanup:
    runs-on: ubuntu-slim
    if: ${{ github.event_name != 'pull_request' }}
    permissions:
      packages: write
    steps:
      - uses: actions/delete-package-versions@v5
        with:
          package-name: mirrorsedgearchive
          package-type: container
          ignore-versions: '^(latest|sandbox)$'
          min-versions-to-keep: 10
